name: Go

on: [push]

defaults:
  run: 
    working-directory: ./go

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: |
          go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test
      - name: Executable file output to
        run: <current-directory>/<name>
      - name: how to run
        run: ./<name>